import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PRECACHE_EXTENSIONS = new Set([
  ".css",
  ".html",
  ".ico",
  ".js",
  ".png",
  ".svg",
  ".webmanifest",
  ".webp",
  ".woff2",
]);

interface PrecacheEntry {
  file: string;
  precache: boolean;
  url: string;
}

export interface PrecacheManifest {
  revision: string;
  urls: string[];
}

function collectPrecacheEntries(
  distRoot: string,
  readDirectory: (directory: string) => fs.Dirent[] = (directory) =>
    fs.readdirSync(directory, { withFileTypes: true }),
): PrecacheEntry[] {
  const files: string[] = [];

  function walk(directory: string): void {
    for (const entry of readDirectory(directory)) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        walk(absolute);
      } else if (entry.isFile()) {
        files.push(absolute);
      }
    }
  }

  walk(distRoot);

  const entries = files
    .map((file) => path.relative(distRoot, file).split(path.sep).join("/"))
    .filter((file) => file !== "404.html" && file !== "sw.js")
    .filter((file) => PRECACHE_EXTENSIONS.has(path.extname(file)))
    .map((file) => {
      let url: string;
      if (file === "index.html") {
        url = "/";
      } else if (file.endsWith("/index.html")) {
        url = `/${file.slice(0, -"index.html".length)}`;
      } else {
        url = `/${file}`;
      }
      return {
        file: path.join(distRoot, file),
        precache:
          path.extname(file) !== ".html" ||
          file === "index.html" ||
          file === "offline.html",
        url,
      };
    });

  const rootIndex = entries.find((entry) => entry.url === "/");
  if (rootIndex) {
    entries.push({ ...rootIndex, url: "/index.html" });
  }

  return [...new Map(entries.map((entry) => [entry.url, entry])).values()].sort(
    (left, right) => left.url.localeCompare(right.url),
  );
}

export function collectPrecacheUrls(
  distRoot: string,
  readDirectory: (directory: string) => fs.Dirent[] = (directory) =>
    fs.readdirSync(directory, { withFileTypes: true }),
): string[] {
  return collectPrecacheEntries(distRoot, readDirectory)
    .filter((entry) => entry.precache)
    .map((entry) => entry.url);
}

export function collectPrecacheManifest(
  distRoot: string,
  readDirectory: (directory: string) => fs.Dirent[] = (directory) =>
    fs.readdirSync(directory, { withFileTypes: true }),
  readFile: (file: string) => Buffer | string = (file) => fs.readFileSync(file),
): PrecacheManifest {
  const entries = collectPrecacheEntries(distRoot, readDirectory);
  const hash = crypto.createHash("sha256");

  for (const entry of entries) {
    hash.update(entry.url);
    hash.update("\0");
    hash.update(readFile(entry.file));
    hash.update("\0");
  }

  return {
    revision: hash.digest("hex").slice(0, 16),
    urls: entries.filter((entry) => entry.precache).map((entry) => entry.url),
  };
}

export function renderServiceWorker(manifest: PrecacheManifest): string {
  const { revision, urls: precacheUrls } = manifest;

  return `/* Generated by scripts/generate-service-worker.ts. */
const REVISION = ${JSON.stringify(revision)};
const PRECACHE = \`murphys-precache-\${REVISION}\`;
const RUNTIME = \`murphys-runtime-\${REVISION}\`;
const PRECACHE_URLS = ${JSON.stringify(precacheUrls)};
const STATIC_FILE_PATTERN = /^\\/[^/]+\\.(txt|xml|json|rss|atom)(\\?.*)?$/;
const IS_CANONICAL_HOST = self.location.hostname === 'murphys-laws.com';

const isCacheable = (response) =>
  Boolean(response) && (response.status === 0 || response.status === 200);

async function trimCache(cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  await Promise.all(keys.slice(0, Math.max(0, keys.length - maxEntries)).map((key) => cache.delete(key)));
}

async function cacheFirst(request, cacheName = RUNTIME, maxEntries) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (isCacheable(response)) {
    const cache = await caches.open(cacheName);
    await cache.put(request, response.clone());
    if (maxEntries) await trimCache(cacheName, maxEntries);
  }
  return response;
}

async function networkFirst(request, cacheName, fallbackUrl) {
  try {
    const response = await fetch(request);
    if (isCacheable(response)) {
      const cache = await caches.open(cacheName);
      await cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await caches.match(request);
    if (cached) return cached;
    if (fallbackUrl) {
      const fallback = await caches.match(fallbackUrl);
      if (fallback) return fallback;
    }
    throw error;
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cached = await caches.match(request);
  const refresh = fetch(request).then(async (response) => {
    if (isCacheable(response)) {
      const cache = await caches.open(cacheName);
      await cache.put(request, response.clone());
    }
    return response;
  });
  return cached || refresh;
}

self.addEventListener('install', (event) => {
  if (!IS_CANONICAL_HOST) {
    event.waitUntil(self.skipWaiting());
    return;
  }
  event.waitUntil(
    caches.open(PRECACHE)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  if (!IS_CANONICAL_HOST) {
    event.waitUntil(
      caches.keys()
        .then((names) => Promise.all(
          names
            .filter((name) => name.startsWith('murphys-'))
            .map((name) => caches.delete(name))
        ))
        .then(() => self.registration.unregister())
    );
    return;
  }
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          .filter((name) => name.startsWith('murphys-') && name !== PRECACHE && name !== RUNTIME)
          .map((name) => caches.delete(name))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  if (!IS_CANONICAL_HOST) return;

  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  const sameOrigin = url.origin === self.location.origin;
  const isApi = url.pathname.startsWith('/api/');

  if (request.mode === 'navigate' && sameOrigin) {
    if (isApi || STATIC_FILE_PATTERN.test(url.pathname + url.search)) return;
    event.respondWith(
      networkFirst(request, RUNTIME, '/index.html')
        .catch(() => caches.match('/offline.html'))
    );
    return;
  }

  if (isApi && /\\/api\\/v1\\/(categories|attributions)/.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request, \`\${RUNTIME}-api-reference\`));
    return;
  }

  if (isApi && /\\/api\\/v1\\/(law-of-day|laws)/.test(url.pathname)) {
    event.respondWith(networkFirst(request, \`\${RUNTIME}-api-laws\`));
    return;
  }

  if (/^https:\\/\\/fonts\\.(googleapis|gstatic)\\.com\\//i.test(url.href)) {
    event.respondWith(cacheFirst(request, \`\${RUNTIME}-fonts\`, 30));
    return;
  }

  if (sameOrigin && /\\.(?:png|jpe?g|svg|gif|webp)$/i.test(url.pathname)) {
    event.respondWith(cacheFirst(request, \`\${RUNTIME}-images\`, 100));
    return;
  }

  if (sameOrigin) {
    event.respondWith(cacheFirst(request));
  }
});
`;
}

export interface GenerateServiceWorkerOptions {
  distRoot: string;
  outputPath: string;
  exists: (file: string) => boolean;
  readDirectory?: (directory: string) => fs.Dirent[];
  readFile?: (file: string) => Buffer | string;
  write: (file: string, contents: string) => void;
  logger: Pick<Console, "log" | "error">;
}

export function runGenerateServiceWorker(
  options: GenerateServiceWorkerOptions,
): 0 | 1 {
  if (!options.exists(options.distRoot)) {
    options.logger.error(
      `Service worker generation failed: ${options.distRoot} not found.`,
    );
    return 1;
  }

  const manifest = collectPrecacheManifest(
    options.distRoot,
    options.readDirectory,
    options.readFile,
  );
  options.write(options.outputPath, renderServiceWorker(manifest));
  options.logger.log(
    `Generated ${options.outputPath} with ${manifest.urls.length} precached URL(s).`,
  );
  return 0;
}

function isMain(): boolean {
  const entry = process.argv[1];
  return Boolean(entry && import.meta.url === new URL(`file://${entry}`).href);
}

if (isMain()) {
  const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
  const distRoot = path.resolve(scriptDirectory, "../dist");
  process.exit(
    runGenerateServiceWorker({
      distRoot,
      outputPath: path.join(distRoot, "sw.js"),
      exists: fs.existsSync,
      write: (file, contents) => fs.writeFileSync(file, contents, "utf8"),
      logger: console,
    }),
  );
}
