CREATE TABLE IF NOT EXISTS law_annotations (
  law_id INTEGER PRIMARY KEY,
  explanation TEXT NOT NULL,
  practical_example TEXT NOT NULL,
  source_label TEXT NOT NULL,
  source_url TEXT NOT NULL,
  reviewed_at TEXT NOT NULL,
  FOREIGN KEY (law_id) REFERENCES laws(id) ON DELETE CASCADE
);

INSERT OR REPLACE INTO law_annotations
  (law_id, explanation, practical_example, source_label, source_url, reviewed_at)
SELECT id, 'Question headlines often trade certainty for curiosity; the wording is a useful prompt to inspect the evidence rather than a universal rule.', 'Before sharing a question headline, read the underlying reporting and check whether its evidence supports a more qualified answer.', 'Reference overview', 'https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines', '2026-07-21'
FROM laws WHERE slug = 'betteridges-law-of-headlines';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Late projects have communication and onboarding costs, so adding people can reduce the time available to finish the work.', 'A team near release assigns newcomers isolated follow-up work instead of interrupting every engineer on the critical path.', 'The Mythical Man-Month', 'https://en.wikipedia.org/wiki/The_Mythical_Man-Month', '2026-07-21' FROM laws WHERE slug = 'brookss-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'A conspicuous story element creates an expectation that it matters; removing unused setup keeps the narrative focused.', 'If a prototype introduces a broken alarm in the first scene, the final story either uses it or cuts it.', 'Reference overview', 'https://en.wikipedia.org/wiki/Chekhov%27s_gun', '2026-07-21' FROM laws WHERE slug = 'chekhovs-gun';
INSERT OR REPLACE INTO law_annotations SELECT id, 'An old rule may encode constraints that are no longer obvious. Understand the original purpose before removing it.', 'Before deleting a validation check, inspect the incident or requirement that caused it to be added.', 'Reference overview', 'https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton%27s_fence', '2026-07-21' FROM laws WHERE slug = 'chestertons-fence';
INSERT OR REPLACE INTO law_annotations SELECT id, 'The saying compares advanced technology with effects an observer cannot explain; it is an observation about perception, not literal magic.', 'A device that translates speech instantly can look impossible to someone unfamiliar with modern language models.', 'Clarke''s three laws', 'https://en.wikipedia.org/wiki/Clarke%27s_three_laws', '2026-07-21' FROM laws WHERE slug = 'sir-arthur-charles-clarke-third-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'System boundaries tend to mirror the communication boundaries of the teams that build them.', 'Two teams with a formal handoff often produce two services with a similarly formal API boundary.', 'How Do Committees Invent?', 'https://www.melconway.com/Home/Committees_Paper.html', '2026-07-21' FROM laws WHERE slug = 'conways-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Posting an incorrect answer can attract corrections faster than asking an open question, but doing so deliberately can erode trust.', 'A troubleshooting post that includes a tentative diagnosis receives focused corrections from domain experts.', 'Reference overview', 'https://en.wikipedia.org/wiki/Ward_Cunningham#Cunningham%27s_Law', '2026-07-21' FROM laws WHERE slug = 'cunninghams-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'The classic formulation says a communications network becomes more valuable as more participants can connect, though real networks rarely follow a perfect square law.', 'A team chat becomes more useful when all collaborating teams can join rather than only one department.', 'Reference overview', 'https://en.wikipedia.org/wiki/Metcalfe%27s_law', '2026-07-21' FROM laws WHERE slug = 'metcalfes-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Working complex systems usually grow from smaller working systems; designing all complexity at once leaves fewer validated assumptions.', 'Launch a reliable single-region service before adding multi-region failover and global routing.', 'Reference overview', 'https://en.wikipedia.org/wiki/John_Gall_(author)#Gall%27s_law', '2026-07-21' FROM laws WHERE slug = 'galls-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Long online discussions become increasingly likely to invoke extreme historical comparisons. It does not say the comparison is automatically invalid.', 'Moderators can redirect a sprawling argument to specific evidence before rhetoric replaces the original topic.', 'Mike Godwin retrospective', 'https://www.wired.com/1994/10/godwin-if-2/', '2026-07-21' FROM laws WHERE slug = 'godwins-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Once a metric becomes a target, people optimize the metric and can weaken its connection to the intended outcome.', 'A support team measured only on ticket closure speed may close tickets before customers are actually helped.', 'Reference overview', 'https://en.wikipedia.org/wiki/Goodhart%27s_law', '2026-07-21' FROM laws WHERE slug = 'goodharts-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Choice time generally increases as the number and complexity of options increase; the effect depends on familiarity and presentation.', 'A checkout presents three clearly differentiated delivery choices instead of a long undifferentiated list.', 'Reference overview', 'https://en.wikipedia.org/wiki/Hick%27s_law', '2026-07-21' FROM laws WHERE slug = 'hicks-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Planning estimates remain vulnerable to hidden work even when teams try to compensate for their usual optimism.', 'A migration estimate includes validation and rollback time, then still reserves contingency for unknown data problems.', 'Reference overview', 'https://en.wikipedia.org/wiki/Hofstadter%27s_law', '2026-07-21' FROM laws WHERE slug = 'hofstadters-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Ideas or technologies that have survived for a long time may be more likely to persist, but the heuristic does not predict every individual case.', 'A maintainer expects a decades-old text format to outlast a newly launched proprietary format.', 'Reference overview', 'https://en.wikipedia.org/wiki/Lindy_effect', '2026-07-21' FROM laws WHERE slug = 'lindys-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'With enough independent reviewers, many defects become easier to identify and characterize; review quality and coordination still matter.', 'An open-source bug report is reproduced across several environments until one contributor isolates the failing condition.', 'Reference overview', 'https://en.wikipedia.org/wiki/Linus%27s_law', '2026-07-21' FROM laws WHERE slug = 'linuss-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Prefer the explanation that accounts for the evidence with the fewest unsupported assumptions; simplest does not mean shortest or easiest.', 'When one configuration change explains a failure, test it before proposing several unrelated simultaneous faults.', 'Stanford Encyclopedia of Philosophy', 'https://plato.stanford.edu/entries/simplicity/', '2026-07-21' FROM laws WHERE slug = 'occams-razor';
INSERT OR REPLACE INTO law_annotations SELECT id, 'The 80/20 split is a memorable approximation for uneven distributions, not a fixed natural constant.', 'A team profiles incidents and finds that a small group of recurring causes produces most support volume.', 'Reference overview', 'https://en.wikipedia.org/wiki/Pareto_principle', '2026-07-21' FROM laws WHERE slug = 'pareto-principle';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Work often grows to consume the time assigned through added scope, refinement, or delay.', 'A review with a two-week deadline accumulates optional edits that would be skipped for a same-day decision.', 'Reference overview', 'https://en.wikipedia.org/wiki/Parkinson%27s_law', '2026-07-21' FROM laws WHERE slug = 'parkinsons-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Groups can spend disproportionate effort on familiar low-stakes details while giving complex high-stakes matters less scrutiny.', 'A steering group approves a major architecture quickly, then debates a button label for an hour.', 'Reference overview', 'https://en.wikipedia.org/wiki/Law_of_triviality', '2026-07-21' FROM laws WHERE slug = 'parkinsons-law-of-triviality';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Promotion based on success in one role can continue until a person reaches a role requiring different skills.', 'A strong engineer becomes a manager without coaching or evidence that people management fits their strengths.', 'Reference overview', 'https://en.wikipedia.org/wiki/Peter_principle', '2026-07-21' FROM laws WHERE slug = 'peter-principle';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Without clear signals of parody, extreme statements online can be difficult to distinguish from sincere ones.', 'A satirical post includes context or labeling when its audience cannot be expected to know the author''s intent.', 'Reference overview', 'https://en.wikipedia.org/wiki/Poe%27s_law', '2026-07-21' FROM laws WHERE slug = 'poes-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'The robustness principle encouraged tolerant receivers, but modern protocol guidance also warns that accepting malformed input can create ambiguity and security risk.', 'An API documents strict input validation while preserving backward compatibility only for explicitly supported older fields.', 'RFC 1122', 'https://www.rfc-editor.org/rfc/rfc1122.html', '2026-07-21' FROM laws WHERE slug = 'postels-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Conflicting instruments can reduce confidence even when either one alone would appear authoritative.', 'Two dashboards report different totals, prompting the team to reconcile definitions before making a decision.', 'Reference overview', 'https://en.wikipedia.org/wiki/Segal%27s_law', '2026-07-21' FROM laws WHERE slug = 'segals-law';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Scientific ideas and discoveries are often named after someone other than the earliest contributor.', 'A project checks primary history rather than assuming an eponym identifies the original discoverer.', 'Stigler paper overview', 'https://en.wikipedia.org/wiki/Stigler%27s_law_of_eponymy', '2026-07-21' FROM laws WHERE slug = 'stiglers-law-of-eponymy';
INSERT OR REPLACE INTO law_annotations SELECT id, 'Attempts to hide public information can draw more attention to it through reporting and resharing.', 'Before threatening publication over criticism, an organization weighs whether the response will amplify the original material.', 'Reference overview', 'https://en.wikipedia.org/wiki/Streisand_effect', '2026-07-21' FROM laws WHERE slug = 'streisand-effect';
