package com.murphyslaws.ui.theme

import androidx.compose.ui.text.ExperimentalTextApi
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontVariation
import androidx.compose.ui.text.font.FontWeight
import com.murphyslaws.R

/**
 * Work Sans variable-font FontFamily for Compose.
 *
 * Backed by the single TTF at `res/font/work_sans_variable.ttf` (added in
 * PR Android-3). The wght axis lets one TTF cover every weight DESIGN.md
 * uses; we register one Font per weight slot so Compose's typography
 * system can resolve `.weight(...)` requests on the family.
 *
 * Variation settings require API 26+, which matches the app's `minSdk`.
 *
 * Hand-authored (not regenerated by export-android-tokens.ts) because the
 * `R.font.*` reference is Android-specific glue, not part of the design
 * contract. The generated `DS.Typography.<level>` text styles reference
 * this `WorkSans` constant.
 */
@OptIn(ExperimentalTextApi::class)
private fun workSansFont(weight: FontWeight, axisWeight: Int): Font = Font(
    resId = R.font.work_sans_variable,
    weight = weight,
    variationSettings = FontVariation.Settings(FontVariation.weight(axisWeight)),
)

val WorkSans: FontFamily = FontFamily(
    workSansFont(FontWeight.Normal, 400),
    workSansFont(FontWeight.Medium, 500),
    workSansFont(FontWeight.SemiBold, 600),
    workSansFont(FontWeight.Bold, 700),
)
